### ISSUE TITLE
LorentzianClassificationProducer  (InvalidOptionError)

### ISSUE THREAD

**Issue by derBG** [techfreaque/octobot-lorentzian-classification#2]
```
 2023-03-26 21:43:19,748 ERROR    LorentzianClassificationProducer 
Traceback (most recent call last):
  File "/home/pi/OctoBot/OctoBot/tentacles/Meta/Keywords/matrix_library/basic_tentacles/basic_modes/mode_base/abstract_producer_base.py", line 141, in call_script
    await self.make_strategy(context, action)
  File "/home/pi/OctoBot/OctoBot/tentacles/Trading/Mode/lorentzian_classification/trading_mode_entry.py", line 46, in make_strategy
    await self.evaluate_lorentzian_classification(
  File "/home/pi/OctoBot/OctoBot/tentacles/Trading/Mode/lorentzian_classification/classification.py", line 194, in evaluate_lorentzian_classification
    _filters: utils.Filter = self._get_all_filters(
  File "/home/pi/OctoBot/OctoBot/tentacles/Trading/Mode/lorentzian_classification/classification.py", line 1243, in _get_all_filters
    ) = self._get_ma_filters(candle_closes, data_length)
  File "/home/pi/OctoBot/OctoBot/tentacles/Trading/Mode/lorentzian_classification/classification.py", line 611, in _get_ma_filters
    tulipy.sma(
  File "/home/pi/.local/lib/python3.8/site-packages/tulipy/__init__.py", line 1045, in sma
    return lib.sma([real], [period])
  File "tulipy/lib/__init__.pyx", line 105, in tulipy.lib._Indicator.__call__
tulipy.lib.InvalidOptionError
 2023-03-26 21:43:19,750 ERROR    LorentzianClassificationProducer Error when running script:  (InvalidOptionError)


```
[OctoBot.log](https://github.com/techfreaque/octobot-lorentzian-classification/files/11072868/OctoBot.log)

**Comment by techfreaque** [comment]
Hey there, thanks for reporting. Can you check if your "Amount of historical live candles" in the TimeFrameStrategyEvaluator are longer than your sma length. Should be usually at least 2x the longest length you are using for indicators. 
I'm gonna add some better error description with the next version.

**Comment by techfreaque** [comment]
I'm gonna close this issue as the latest version has better error messages for this case.
