### ISSUE TITLE
 Error when displaying page: 'ascii' codec can't decode byte 0xc2 in position 78: ordinal not in range(128) (UnicodeDecodeError)

### ISSUE THREAD

**Issue by wtc0der** [techfreaque/octobot-lorentzian-classification#3]
Hi.

> Debian 11
> python 3.9
> OctoBot 0.4.47

This error occure when I select the profile "lorentzian-classification", just after I'd installed it : 

![image](https://user-images.githubusercontent.com/11579146/230321646-d1653b91-760d-4e21-8f1d-0efde8bb0806.png)

`
2023-04-06 10:28:19 ERROR  WebInterfaceErrorHandler errors.py:34       'ascii' codec can't decode byte 0xc2 in position 78: ordinal not in range(128)
Traceback (most recent call last):
  File "octobot_tentacles_manager/loaders/tentacle_loading.py", line 84, in get_documentation
KeyError: 'LorentzianClassificationMode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 2528, in wsgi_app
  File "flask/app.py", line 1825, in full_dispatch_request
  File "flask/app.py", line 1823, in full_dispatch_request
  File "flask/app.py", line 1799, in dispatch_request
  File "/root/tentacles/Services/Interfaces/web_interface/login/web_login_manager.py", line 98, in decorated_view
    return _login_required_func(func, *args, **kwargs)
  File "flask_login/utils.py", line 290, in decorated_view
  File "/root/tentacles/Services/Interfaces/web_interface/login/web_login_manager.py", line 91, in _login_required_func
    return func(*args, **kwargs)
  File "/root/tentacles/Services/Interfaces/web_interface/controllers/configuration.py", line 80, in profile
    strategy_config=models.get_strategy_config(media_url, missing_tentacles),
  File "/root/tentacles/Services/Interfaces/web_interface/models/configuration.py", line 581, in get_strategy_config
    strategy_config, strategy_config_classes = _get_strategy_activation_state(with_trading_modes,
  File "/root/tentacles/Services/Interfaces/web_interface/models/configuration.py", line 249, in _get_strategy_activation_state
    strategy_config[TRADING_MODES_KEY][key][DESCRIPTION_KEY] = get_tentacle_documentation(key, media_url)
  File "/root/tentacles/Services/Interfaces/web_interface/models/configuration.py", line 210, in get_tentacle_documentation
    doc_content = tentacles_manager_api.get_tentacle_documentation(name)
  File "octobot_tentacles_manager/api/inspector.py", line 67, in get_tentacle_documentation
  File "octobot_tentacles_manager/loaders/tentacle_loading.py", line 90, in get_documentation
  File "encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 78: ordinal not in range(128)
2023-04-06 10:28:19 ERROR  WebInterfaceErrorHandler errors.py:34       Error when displaying page: 'ascii' codec can't decode byte 0xc2 in position 78: ordinal not in range(128) (UnicodeDecodeError)
`

Thank you !

**Comment by techfreaque** [comment]
Hey there,

thanks for reporting, I just pushed a new version that might fix your issue (v-1.2.4).
I was not able to reproduce it, so I'm not sure.
Might be because you're using python 3.9. 

Currently i'm only testing it with 3.8 and 3.10 and Octobot is only supporting 3.8 officially, so you might wanna use that instead.

**Comment by wtc0der** [comment]
Nice, thank you for your advices about Python version.
We can close this issue, the new version work perfectly, thank you very much !

**Comment by techfreaque** [comment]
Awesome, hope you enjoy it :)
