### ISSUE TITLE
Cant import tentacles

### ISSUE THREAD

**Issue by Greatguy2** [techfreaque/octobot-lorentzian-classification#6]
2023-10-31 01:13:00 ERROR  octobot_tentacles_manager.api.util.tentacles_management logging_util.py:227      
Traceback (most recent call last):
  File "octobot_tentacles_manager\api\util\tentacles_management.py", line 28, in manage_tentacles
  File "octobot_commons\authentication.py", line 83, in get_aiohttp_session
NotImplementedError
2023-10-31 01:13:00 ERROR  octobot_tentacles_manager.api.util.tentacles_management logging_util.py:204      Exception during InstallWorker processing:  (error: NotImplementedError)

**Comment by MarwanYouness** [comment]
any luck on this one?

**Comment by techfreaque** [comment]
Hey there, sorry I forgot to close this issue. This is fixed since a long time already
